# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea136e819a80ad8d0203f691824117b6f249a571037d60fcea25712b9aa64a5fc4c6f154103b6b72d4001e946b8937d05ded1fc451061ccd914fe28ca93abf15

test:
  secret_key_base: b077a34680e0218c7090dc7d9bc80946547a02d2fac8943aa0cb7c2c13db4dcacdcfc118f99730ad814a452743d234bd0bfd91014b3e0a432a933529f900f13a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
